# Utilizar una imagen base de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo requirements.txt dentro del contenedor
COPY requirements.txt .

# Instalar las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el código de la aplicación dentro del contenedor
COPY . .

# Comando para ejecutar el script principal
CMD ["python", "main.py", "--models", "gru"]